// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package setup

import (
	"go.mongodb.org/mongo-driver/mongo"
	"guardian/api"
	"guardian/internal/repository"
	"guardian/internal/services"
)

// Injectors from wire.go:

func InitializeSendHandlerController(db *mongo.Database) *api.SendHandlerController {
	userTaskRepository := repository.NewUserTasksRepository(db)
	userTaskService := services.NewUserTaskService(userTaskRepository)
	promptService := services.NewPromptService(userTaskService)
	sendHandlerController := api.NewSendHandlerController(promptService)
	return sendHandlerController
}
