// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package setup

import (
	"github.com/google/wire"
	"go.mongodb.org/mongo-driver/mongo"
	"guardian/api"
	"guardian/internal/repository"
	"guardian/internal/services"
)

// Injectors from wire.go:

func InitializeSendHandlerController(db *mongo.Database) *api.SendHandlerController {
	userRepository := repository.NewUserRepository(db)
	taskRepository := repository.NewTaskRepository(db)
	userService := NewUserService(userRepository, taskRepository)
	promptService := services.NewPromptService(userService)
	targetModelRepository := repository.NewTargetModelRepository(db)
	targetModelService := services.NewTargetModelService(targetModelRepository)
	sendHandlerController := api.NewSendHandlerController(promptService, targetModelService)
	return sendHandlerController
}

func InitializeAuthController(db *mongo.Database) *api.AuthController {
	userRepository := repository.NewUserRepository(db)
	taskRepository := repository.NewTaskRepository(db)
	userService := services.NewUserService(userRepository, taskRepository)
	authController := api.NewAuthController(userService)
	return authController
}

// wire.go:

func NewUserService(userRepo *repository.UserRepository, taskRepo *repository.TaskRepository) *services.UserService {
	return services.NewUserService(userRepo, taskRepo)
}

var UserServiceSet = wire.NewSet(
	NewUserService, wire.Bind(new(services.UserServiceInterface), new(*services.UserService)),
)

var SendHandlerSet = wire.NewSet(api.NewSendHandlerController, services.NewPromptService, UserServiceSet, repository.NewTaskRepository)
